services:
  web:
    build:
      context: .
      target: dev
    container_name: team3app-web-dev
    ports: ["3000:3000"]
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules
volumes:
  node_modules_cache:
