services:
  web:
    build:
      context: .
      target: dev
    container_name: team3app-web-dev
    ports: ["3000:3000"]
    # Compose で .env を読み込み（後勝ちで上書き）
    env_file:
      - .env.common
      - .env.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - node_modules_cache:/app/node_modules

  db:
    image: postgres:17-alpine
    container_name: team3app-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devpass}
      POSTGRES_DB: ${POSTGRES_DB:-team3app_dev}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  node_modules_cache:
  pgdata:
