CREATE TABLE IF NOT EXISTS "tag_types" (
    "id" smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" text NOT NULL UNIQUE,
    "label" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN IF NOT EXISTS "tag_type_id" smallint;
--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now() NOT NULL;
--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN IF NOT EXISTS "updated_at" timestamp with time zone DEFAULT now() NOT NULL;
--> statement-breakpoint
INSERT INTO "tag_types" ("code", "label")
VALUES ('unknown', '未分類')
ON CONFLICT ("code") DO NOTHING;
--> statement-breakpoint
DO $$
DECLARE
    v_unknown_id smallint;
BEGIN
    SELECT id INTO v_unknown_id FROM tag_types WHERE code = 'unknown';
    IF v_unknown_id IS NULL THEN
        RAISE EXCEPTION 'unknown tag_type_id not found';
    END IF;
    UPDATE tags SET tag_type_id = v_unknown_id WHERE tag_type_id IS NULL;
    EXECUTE format('ALTER TABLE tags ALTER COLUMN tag_type_id SET DEFAULT %s', v_unknown_id);
END $$;
--> statement-breakpoint
ALTER TABLE "tags" ALTER COLUMN "tag_type_id" SET NOT NULL;
--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "tags" ADD CONSTRAINT "tags_tag_type_id_tag_types_id_fk" FOREIGN KEY ("tag_type_id") REFERENCES "public"."tag_types"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
ALTER TABLE "chat_tags" ADD COLUMN IF NOT EXISTS "confidence" real DEFAULT 0 NOT NULL;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user_tag_mastery" (
    "user_id" uuid NOT NULL,
    "tag_id" uuid NOT NULL,
    "mastery_score" real DEFAULT 0 NOT NULL,
    "last_assessed_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "user_tag_mastery_user_id_tag_id_pk" PRIMARY KEY ("user_id", "tag_id")
);
--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_tag_mastery" ADD CONSTRAINT "user_tag_mastery_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
    ALTER TABLE "user_tag_mastery" ADD CONSTRAINT "user_tag_mastery_tag_id_tags_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_tag_mastery_user_idx" ON "user_tag_mastery" ("user_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_tag_mastery_tag_idx" ON "user_tag_mastery" ("tag_id");
