name: "✨ Feature Request (機能要望)"
description: "新しい機能や改善を提案します"
title: "[FEAT]: "
labels: ["enhancement", "feature-request"]
body:
  - type: textarea
    id: problem-description
    attributes:
      label: "どのような機能ですか？ (Is your feature request related to a problem?)"
      description: "解決したい課題や、不便に感じている点を記述してください。"
      placeholder: "例: 〇〇ができず不便なので、〇〇という機能がほしい"
    validations:
      required: true
  - type: textarea
    id: solution-proposal
    attributes:
      label: "解決策の提案 (Describe the solution you'd like)"
      description: "具体的にどのような機能・UI/UXを期待しているか記述してください。"
      placeholder: "例: ヘッダーに〇〇ボタンを追加し、クリックすると〇〇のモーダルが表示される"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "代替案 (Describe alternatives you've considered)"
      description: "検討した他の解決策や代替案があれば記述してください。"
  - type: textarea
    id: additional-context
    attributes:
      label: "その他 (Additional Context)"
      description: "その他、機能の実現に役立つ情報があれば記述してください。"